services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://host.docker.internal:3000
      # - CHOKIDAR_USEPOLLING=true
      # 윈도우에서 필요하다고 함. 안되면 넣을 것.
    command: ["npm", "run", "dev"] # Ensure it runs the correct command in the container
